# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule GoogleApi.CloudBuild.V1.Model.Build do
  @moduledoc """
  A build resource in the Cloud Build API.  At a high level, a &#x60;Build&#x60; describes where to find source code, how to build it (for example, the builder image to run on the source), and where to store the built artifacts.  Fields can include the following variables, which will be expanded when the build is created:  - $PROJECT_ID: the project ID of the build. - $BUILD_ID: the autogenerated ID of the build. - $REPO_NAME: the source repository name specified by RepoSource. - $BRANCH_NAME: the branch name specified by RepoSource. - $TAG_NAME: the tag name specified by RepoSource. - $REVISION_ID or $COMMIT_SHA: the commit SHA specified by RepoSource or   resolved from the specified branch or tag. - $SHORT_SHA: first 7 characters of $REVISION_ID or $COMMIT_SHA.

  ## Attributes

  - tags ([String.t]): Tags for annotation of a &#x60;Build&#x60;. These are not docker tags. Defaults to: `null`.
  - artifacts (Artifacts): Artifacts produced by the build that should be uploaded upon successful completion of all build steps. Defaults to: `null`.
  - buildTriggerId (String.t): Output only. The ID of the &#x60;BuildTrigger&#x60; that triggered this build, if it was triggered automatically. Defaults to: `null`.
  - createTime (DateTime.t): Output only. Time at which the request to create the build was received. Defaults to: `null`.
  - finishTime (DateTime.t): Output only. Time at which execution of the build was finished.  The difference between finish_time and start_time is the duration of the build&#39;s execution. Defaults to: `null`.
  - id (String.t): Output only. Unique identifier of the build. Defaults to: `null`.
  - images ([String.t]): A list of images to be pushed upon the successful completion of all build steps.  The images are pushed using the builder service account&#39;s credentials.  The digests of the pushed images will be stored in the &#x60;Build&#x60; resource&#39;s results field.  If any of the images fail to be pushed, the build status is marked &#x60;FAILURE&#x60;. Defaults to: `null`.
  - logUrl (String.t): Output only. URL to logs for this build in Google Cloud Console. Defaults to: `null`.
  - logsBucket (String.t): Google Cloud Storage bucket where logs should be written (see [Bucket Name Requirements](https://cloud.google.com/storage/docs/bucket-naming#requirements)). Logs file names will be of the format &#x60;${logs_bucket}/log-${build_id}.txt&#x60;. Defaults to: `null`.
  - options (BuildOptions): Special options for this build. Defaults to: `null`.
  - projectId (String.t): Output only. ID of the project. Defaults to: `null`.
  - results (Results): Output only. Results of the build. Defaults to: `null`.
  - secrets ([Secret]): Secrets to decrypt using Cloud Key Management Service. Defaults to: `null`.
  - source (Source): The location of the source files to build. Defaults to: `null`.
  - sourceProvenance (SourceProvenance): Output only. A permanent fixed identifier for source. Defaults to: `null`.
  - startTime (DateTime.t): Output only. Time at which execution of the build was started. Defaults to: `null`.
  - status (String.t): Output only. Status of the build. Defaults to: `null`.
    - Enum - one of [STATUS_UNKNOWN, QUEUED, WORKING, SUCCESS, FAILURE, INTERNAL_ERROR, TIMEOUT, CANCELLED]
  - statusDetail (String.t): Output only. Customer-readable message about the current status. Defaults to: `null`.
  - steps ([BuildStep]): Required. The operations to be performed on the workspace. Defaults to: `null`.
  - substitutions (%{optional(String.t) &#x3D;&gt; String.t}): Substitutions data for &#x60;Build&#x60; resource. Defaults to: `null`.
  - timeout (String.t): Amount of time that this build should be allowed to run, to second granularity. If this amount of time elapses, work on the build will cease and the build status will be &#x60;TIMEOUT&#x60;.  Default time is ten minutes. Defaults to: `null`.
  - timing (%{optional(String.t) &#x3D;&gt; TimeSpan}): Output only. Stores timing information for phases of the build. Valid keys are:  * BUILD: time to execute all build steps * PUSH: time to push all specified images. * FETCHSOURCE: time to fetch source.  If the build does not specify source or images, these keys will not be included. Defaults to: `null`.
  """

  @type t :: %__MODULE__{
          tags: any(),
          artifacts: GoogleApi.CloudBuild.V1.Model.Artifacts.t(),
          buildTriggerId: any(),
          createTime: any(),
          finishTime: any(),
          id: any(),
          images: any(),
          logUrl: any(),
          logsBucket: any(),
          options: GoogleApi.CloudBuild.V1.Model.BuildOptions.t(),
          projectId: any(),
          results: GoogleApi.CloudBuild.V1.Model.Results.t(),
          secrets: list(GoogleApi.CloudBuild.V1.Model.Secret.t()),
          source: GoogleApi.CloudBuild.V1.Model.Source.t(),
          sourceProvenance: GoogleApi.CloudBuild.V1.Model.SourceProvenance.t(),
          startTime: any(),
          status: any(),
          statusDetail: any(),
          steps: list(GoogleApi.CloudBuild.V1.Model.BuildStep.t()),
          substitutions: any(),
          timeout: any(),
          timing: map()
        }

  defstruct [
    :tags,
    :artifacts,
    :buildTriggerId,
    :createTime,
    :finishTime,
    :id,
    :images,
    :logUrl,
    :logsBucket,
    :options,
    :projectId,
    :results,
    :secrets,
    :source,
    :sourceProvenance,
    :startTime,
    :status,
    :statusDetail,
    :steps,
    :substitutions,
    :timeout,
    :timing
  ]
end

defimpl Poison.Decoder, for: GoogleApi.CloudBuild.V1.Model.Build do
  import GoogleApi.CloudBuild.V1.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:artifacts, :struct, GoogleApi.CloudBuild.V1.Model.Artifacts, options)
    |> deserialize(:createTime, :date, nil, options)
    |> deserialize(:finishTime, :date, nil, options)
    |> deserialize(:options, :struct, GoogleApi.CloudBuild.V1.Model.BuildOptions, options)
    |> deserialize(:results, :struct, GoogleApi.CloudBuild.V1.Model.Results, options)
    |> deserialize(:secrets, :list, GoogleApi.CloudBuild.V1.Model.Secret, options)
    |> deserialize(:source, :struct, GoogleApi.CloudBuild.V1.Model.Source, options)
    |> deserialize(
      :sourceProvenance,
      :struct,
      GoogleApi.CloudBuild.V1.Model.SourceProvenance,
      options
    )
    |> deserialize(:startTime, :date, nil, options)
    |> deserialize(:steps, :list, GoogleApi.CloudBuild.V1.Model.BuildStep, options)
    |> deserialize(:timing, :map, GoogleApi.CloudBuild.V1.Model.TimeSpan, options)
  end
end

defimpl Poison.Encoder, for: GoogleApi.CloudBuild.V1.Model.Build do
  def encode(value, options) do
    GoogleApi.CloudBuild.V1.Deserializer.serialize_non_nil(value, options)
  end
end
